[package]
name = "dose-response"
version = "0.5.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
license = "GPL-3.0"
build = "build.rs"
exclude = ["scripts/*", "replays/*", "screenshots/*"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
bitflags = "1.0"

rand = "0.4.1"

clap = { version = "2.20.1", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

chrono = { version = "0.4.0", optional = true }
tcod = { git = "https://github.com/tomassedovic/tcod-rs", optional = true }
rustbox = { version = "0.9.0", optional = true }
piston_window = { version = "0.63.0", optional = true }
image = { version = "0.12.2", optional = true }
glium = { version = "0.18.1", optional = true }
zmq = { version = "0.8", optional = true }

[dependencies.num-rational]
version = "0.1.40"
default-features = false

[build-dependencies]
rusttype = "0.2.1"
image = "0.12.2"


[features]

default = ["opengl", "cli", "replay"]

cli = ["clap"]

web = []

replay = ["chrono"]

piston = ["piston_window", "image"]

opengl = ["glium", "image"]

terminal = ["rustbox"]

libtcod = ["tcod"]

remote = ["zmq"]
