[package]
name = "dose-response"
version = "0.4.3"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
license = "GPL-3.0"
build = "build.rs"
exclude = ["scripts/*", "replays/*", "screenshots/*"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
bitflags = "1.0"
time = "0.1.35"
rand = "0.3.14"
clap = "2.20.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

tcod = { git = "https://github.com/tomassedovic/tcod-rs", optional = true }
rustbox = { version = "0.9.0", optional = true }
piston_window = { version = "0.63.0", optional = true }
image = { version = "0.12.2", optional = true }
glium = { version = "0.17.0", optional = true }
zmq = { version = "0.8", optional = true }

[build-dependencies]
rusttype = "0.2.1"
image = "0.12.2"


[features]

default = ["opengl"]

piston = ["piston_window", "image"]

opengl = ["glium", "image"]

terminal = ["rustbox"]

libtcod = ["tcod"]

remote = ["zmq"]
