[package]
name = "dose-response"
version = "0.8.3"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
license = "GPL-3.0"
build = "build.rs"
exclude = ["scripts/*", "replays/*", "screenshots/*", "ci/*",
           "web-src/*", "*.js", "*.css", "*.html",
           "notes.org", "SAVEDGAME.sav", "out-dir-path"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
bitflags = "1.0"

clap = { version = "2.20.1", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# We use this to serialise the game save state into a binary format
bincode = "1.0"
chrono = { version = "0.4.0", optional = true }
image = { version = "0.12.2", optional = true }
#glium = { version = "0.21", optional = true }
glium = { git = "https://github.com/tomassedovic/glium", optional = true }
sdl2 = { version = "0.31.0", features = ["bundled"], optional = true }
gl = { version = "0.10", optional = true }
zmq = { version = "0.8", optional = true }

[dependencies.num-rational]
version = "0.1.40"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = { version = "0.5.0-pre.2", features = ["serde1"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.5.0-pre.2", default-features = false, features = ["serde1"] }

[build-dependencies]
rusttype = "0.2.1"
image = "0.12.2"


[features]

default = ["opengl", "cli", "replay", "rand", "fullscreen", "cheating", "stats", "verifications"]

fullscreen = []

cheating = []

stats = []

cli = ["clap"]

web = []

replay = ["chrono"]

verifications = []

opengl = ["glium", "image"]

sdl = ["sdl2", "gl", "image"]

remote = ["zmq"]


[profile.release]
codegen-units = 1
# NOTE: this should make the binaries smaller and faster at some compile time cost. Read up on it, profile, verify!
#lto = true
