max_width = 80
struct_lit_width = 30
write_mode = "Overwrite"
wrap_comments = true
reorder_imports = true
reorder_imported_names = true
array_layout = "Block"
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = false
closure_block_indent_threshold = 1
